### PR TITLE
Interactive console mode

### PR DESCRIPTION
**Pull request by drakes00**
Hi, I went accross few challenges for which I needed the possibility to perform custom transformations on samples and results.
I implemented it using an embedded shell that brings you back on default prompt on exit.
For example it is useful to apply custom lambda to all samples (e.g.: to encode and decode).

Cheer,
Maxime

### CODE REVIEW

**Comment by drakes00** [comment]
Didn't mentioned in comment but unpacking of results in RSA Wiener was failing.
I added a star according to: http://stackoverflow.com/a/40894725

However, it might be needed at other places.

**Comment by drakes00** [comment]
Also, it is specified in README: "specifically the ability to import a file with newline-separated samples where each line will be treated as a distinct sample".
However it fails on this file: https://cryptopals.com/static/challenge-data/4.txt

FeatherDuster> import singlefile
Please enter the filename you want to open: challs/4.txt

FeatherDuster> console 
In [1]: len(feathermodules.samples)
Out[1]: 1

**Comment by unicornsasfuel** [comment]
I love IPython and an embedded console makes sense, but I'm reluctant to introduce another dependency to FeatherDuster. Is there some way to make this an optional dependency, where the console is not available or only the vanilla console is available if IPython is not installed?

**Comment by drakes00** [comment]
To the best of my knowledge, that's actually what the code import is doing: try to import IPython if any or rely on standard code module if it fails.

I understand the dependency problem and if I'm not mistaking, code is a standard module since it appears in this list: https://docs.python.org/2.7/library/

What I propose, I'll install a fresh VM with basic python and see if I get any problem (e.g.: code module is missing) and you'll choose to merge or not depending on the results.

**Comment by unicornsasfuel** [comment]
Oh! I'm sorry, you're totally right. Don't worry yourself with the VM, I'm happy merging this now.

Thanks again!

**Pull request merged**
